### ISSUE TITLE
OS2

### ISSUE THREAD

**Issue by Tellie** [moose-kazan/qbr#1]
Hi
I tried to compile to OS2
Using Qt6.2.12 and cmake 3.31
But i get this error when compiling it:
[ 94%] Building CXX object CMakeFiles/qbr.dir/qbr_autogen/UVLADIE3JM/qrc_qbr.cpp.o
f:/qbr/src/export/exportmarkdown.cpp: In member function 'virtual void ExportMarkdown::setData(QBRBook*)':
f:/qbr/src/export/exportmarkdown.cpp:17:25: error: 'markdownLinesSrc' was not declared in this scope
   17 |     for (int i = 0; i < markdownLinesSrc.count(); i++) {
      |                         ^~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/qbr.dir/build.make:496: CMakeFiles/qbr.dir/src/export/exportmarkdown.cpp.o] Error 1

Any thoughts ??

Kind regards, TeLLie

**Comment by moose-kazan** [comment]
"Export to Markdown" works only with Qt 6.4 and newer. It must not build with Qt older than 6.4, but i broke it in ec7012a22051fb2ebe2c7e53060e3bdd6c323b05.

Fixed in 0b951548bbe1c90f200264a8abf13589b7f2242d

Please try to pool latest version of main.

**Comment by Tellie** [comment]
Hi

Thankz for the fast answer.
This fix the error

Tellie

Op di 16 sep 2025, 23:05 schreef MooSE ***@***.***>:

**Comment by moose-kazan** [comment]
Good news)

Thank you for your report.
